### ISSUE TITLE
NotFoundError: No Services matching UUID 78290001-d52e-473f-a9f4-f03da7c67dd1 found in Device.

### ISSUE THREAD

**Issue by Swordstone86** [DanTheMan827/ntag215-puck.js#3]
The puck doesn't seem to be properly advertising its service. When paired with the web frontend, the "connecting" dialog show up, followed by the following error message after some time:

`NotFoundError: No Services matching UUID 78290001-d52e-473f-a9f4-f03da7c67dd1 found in Device.`

Puck.js firmware version: `2v09`

Steps to reproduce:
1. Upload the code contained within `ntag215.js` to the puck via the Espruino Web IDE
2. The following console output is received: 
```
Fixed bad bcc
BLE Connected, queueing BLE restart for later
```
3. Disconnect the puck from the Espruino Web IDE and attempt to pair from the puck management page
4. The puck will appear for pairing, and the website will attempt to connect, but the NotFoundError will be thrown.

**Comment by mmarquez76** [comment]
Hi, any update on this? I'm having the same issue and I'm wondering if it's just something I'm doing wrong.

**Comment by Swordstone86** [comment]
Update on this: it turned out to be something buggy with my PC's bluetooth adapter. When I tried using the tool on my phone, it worked great. Thanks!
